---
platform: linux

image_resource:
  type: docker-image
  source: {repository: takuanosho/openresty-builder}

inputs:
  - name: openresty-builder

outputs:
  - name: rpm-package

run:
  path: openresty-builder/scripts/build-openresty.sh

params:
  OUTPUTS_NAME: rpm-package
