---
platform: linux

image: docker:///takuanosho/openresty-builder

inputs:
- name: openresty-builder

run:
  path: openresty-builder/scripts/build-openresty.sh

params:
  OPENRESTY_VERSION: 1.9.7.4
  PCRE_VERSION: 8.38
  OPENSSL_VERSION: 1.0.2g
  ZLIB_VERSION: 1.2.8
