---
platform: linux
image_resource:
  type: docker-image
  source: {repository: alpine}
inputs:
  - name: openresty-builder
  - name: rpm-package
run:
  path: openresty-builder/scripts/send-to-repository.sh
params:
  INPUTS_NAME: rpm-package
