---
platform: linux

image: docker:///takuan-osho/openresty-builder

inputs:
  - name: openresty-builder-resource

run:
  path: openresty-builder-resource/build-openresty/build.sh

resources:
- name: openresty-builder-resource
  type: git
  source:
    uri: https://github.com/takuan-osho/concourse-sample.git
