---
resources:
- name: openresty-builder-resource
  type: git
  source:
    uri: https://github.com/takuan-osho/concourse-sample.git
    private_key: {{github-private-key}}

- name: openresty-builder-docker-image
  type: docker-image
  source:
    repository: {{docker-hub-openresty-builder}}


jobs:
- name: build-openresty
  serial: true
  plan:
  - aggregate:
    - get: openresty-builder-docker-image
    - get: openresty-builder-resource
      trigger: true
  - task: build-openresty
    file: openresty-builder-resource/build-openresty/build.yml
